# Define base image
FROM public.ecr.aws/docker/library/python:3.13.0a4-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# # Copy environment variables from ConfigMap
# COPY --from=config /config/*.env .
# RUN source /config/*.env

# Copy application code
COPY . .

# Run the application
CMD ["python", "app.py"]
