# Define base image
FROM public.ecr.aws/docker/library/python:3.12

# Set working directory
WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev build-essential
ARG DB_USERNAME
ARG DB_PASSWORD

ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD

RUN echo $DB_USERNAME

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# # Copy environment variables from ConfigMap
# COPY --from=config /config/*.env .
# RUN source /config/*.env

# Copy application code
COPY . .

# Run the application
CMD ["python", "app.py"]
