version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies.. ."
      - yum install -y docker gettext jq
  build:
    commands:
      - username=$(echo "$secret" | jq -r '.username')
      - password=$(echo "$secret" | jq -r '.password')
      - echo "Building Docker image... $username"
      - export DB_USERNAME="$username"
      - export DB_PASSWORD="$password"
      - docker build -t 597532192256.dkr.ecr.us-east-1.amazonaws.com/tin-udacity-repo/analytics-tin:latest ./analytics
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account | jq -r)
      - aws ecr get-authorization-token --registry-ids $AWS_ACCOUNT_ID | jq -r '.authorizationData[0].authorizationToken' | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
      - docker push 597532192256.dkr.ecr.us-east-1.amazonaws.com/tin-udacity-repo/analytics-tin:latest
env:
  secrets-manager:
    secret: tincitosql
