apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: tincito-udacity
  region: us-east-1
  version: "1.29"

iam:
  withOIDC: true

managedNodeGroups:
  - name: managed-ng-public
    instanceType: t3.medium
    minSize: 1
    desiredCapacity: 1
    maxSize: 4
    volumeSize: 50
    updateConfig:
      maxUnavailable: 1
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/tinGitlab.pub
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        ebs: true
        fsx: true
        efs: true
        cloudWatch: true

addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
